version: '3'
services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    image: ${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
    build: .
    env_file:
      - .env
    ports:
      - ${APP_TARGET_PORT}:80/tcp
    volumes:
     - .:/project
