name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Remove empty submodule forlder
      run: rm -r -f ./uni_devops_flask_application
    - name: clone submodule
      run: git clone https://github.com/N10100010/uni_devops_flask_application.git
    - name: Build contianer
      run: docker-compose build
